services:
# nexus have 2 port
# - 8081 : for UI
# - 5000 : for docker images registery
  nexus-svc:
    image: sonatype/nexus3
    container_name: nexus_cont
    ports: 
      - 8081:8081
      - 5000:5000
    volumes:
      - nexus-vol:/nexus/data
    restart: always
volumes:
  nexus-vol: 
